### ISSUE TITLE
GPG validation of packages ignored.

### ISSUE THREAD

**Issue by gnif** [hfm/puppet-percona#10]
https://github.com/hfm/puppet-percona/blob/b159df6a0a2fcffb58ad9fb18865cc97d01004a4/manifests/xtrabackup.pp#L34

This is extremely unsafe, do not do this. Please fix the apt gpg key:

https://github.com/hfm/puppet-percona/blob/b159df6a0a2fcffb58ad9fb18865cc97d01004a4/manifests/repo/apt.pp#L14

Change to:

    id => '4D1BB29D63D98E422B2113B19334A25F8507EFA5',
    server => 'keyserver.ubuntu.com'

**Comment by hfm** [comment]
@gnif Thank you for letting me know.
I fixed by #11 and released [v0.2.0](https://forge.puppet.com/hfm/percona/0.2.0).

**Comment by gnif** [comment]
Looks good thanks. In future you should add to your commit comment `Fixes #N` where N is the issue number. GitHub will automatically mark the issue as resolved and reference it if you do this.
